[build-system]
requires = [
    "setuptools>=77.0.3",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[project]
name = "chesscalc"
version = "2.0.3"
authors = [
  { name="Roger Marsh", email="roger.marsh@solentware.co.uk" },
]
description = "Calculate player performances in chess games."
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Games/Entertainment :: Board Games",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Developers",
    "Development Status :: 3 - Alpha",
]
license = "BSD-3-Clause"
license-files = ["LICENCE"]
readme = "README"
dependencies = [
    "solentware-misc==1.7.2",
    "solentware-base==5.2.3",
    "solentware-grid==3.0.2",
    "pgn-read==2.5",
]

[project.urls]
Homepage = "http://www.solentware.co.uk"
Repository = "https://github.com/RogerMarsh/chesscalc.git"
"Bug Tracker" = "https://github.com/RogerMarsh/chesscalc/issues"

[tool.setuptools]
packages = [
    "chesscalc",
    "chesscalc.core",
    "chesscalc.basecore",
    "chesscalc.apsw",
    "chesscalc.berkeleydb",
    "chesscalc.db",
    "chesscalc.db_tkinter",
    "chesscalc.dpt",
    "chesscalc.lmdb",
    "chesscalc.sqlite",
    "chesscalc.unqlite",
    "chesscalc.vedis",
    "chesscalc.gui",
    "chesscalc.shared",
    "chesscalc.legacy",
    "chesscalc.legacy.gui",
    "chesscalc.legacy.core",
    "chesscalc.help_",
]

[tool.setuptools.package-data]
chesscalc = ["help_/*.txt"]
